import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import { UserProvider } from '../context/user/userContext';
import { AppProvider } from '../context/app/appContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'NextImmo',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <AppProvider>
          <UserProvider>
            <Navbar />
            {children}
            <Footer />
          </UserProvider>
        </AppProvider>
      </body>
    </html>
  );
}
